/**
 * Convert simple markdown to HTML suitable for ADO work item fields.
 * ADO expects HTML in System.Description and AcceptanceCriteria fields.
 * This handles the common markdown patterns generated by LLMs in task details:
 * - Headings (#, ##, ###)
 * - Bold (**text**), italic (*text*)
 * - Unordered lists (- item)
 * - Ordered lists (1. item) — including mixed bullet/numbered sequences
 * - Line breaks
 * - Code blocks and inline code
 * - Links
 * - Checkboxes (- [x] / - [ ])
 *
 * Line-based parser: consecutive `- ` lines become one <ul>, consecutive
 * `N. ` lines become one <ol>, and a tag switch flushes the open list — the
 * old regex heuristic (`(<li>.*</li>)+` with a greedy `.*`) merged mixed
 * lists into the wrong wrapper or left bare <li> outside any list, which ADO
 * renders as broken HTML.
 */

export function markdownToHtml(md: string): string {
  if (!md) return '';

  // Escape HTML entities first (we don't want markdown to produce XSS)
  let html = md
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  // Protect code blocks so newline/list processing can't touch them.
  // Placeholders use private-use characters (\uE000/\uE001) — never valid in
  // markdown source, and not control chars (no-control-regex).
  const codeBlocks: string[] = [];
  html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (_m, lang, code) => {
    const langAttr = lang ? ` class="language-${lang}"` : '';
    codeBlocks.push(`<pre><code${langAttr}>${code.trim()}</code></pre>`);
    return `\uE000${codeBlocks.length - 1}\uE001`;
  });

  /** Inline transforms applied to a single text fragment. */
  const inline = (text: string): string => text
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');

  const out: string[] = [];
  let list: { tag: 'ul' | 'ol'; items: string[] } | null = null;
  let para: string[] = [];

  const flushList = (): void => {
    if (!list) return;
    out.push(`<${list.tag}>${list.items.map(i => `<li>${i}</li>`).join('')}</${list.tag}>`);
    list = null;
  };
  const flushPara = (): void => {
    if (para.length === 0) return;
    out.push(`<p>${para.join('<br>')}</p>`);
    para = [];
  };

  for (const rawLine of html.split('\n')) {
    const line = rawLine.trimEnd();

    // Code block placeholder
    const codeMatch = line.match(/^\uE000(\d+)\uE001/);
    if (codeMatch) {
      flushList();
      flushPara();
      out.push(codeBlocks[Number(codeMatch[1])]);
      continue;
    }

    // Headings (#, ##, ###)
    const heading = line.match(/^(#{1,3})\s+(.+)$/);
    if (heading) {
      flushList();
      flushPara();
      out.push(`<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`);
      continue;
    }

    // Horizontal rule (---, ***, ___)
    if (/^[-*_]{3,}$/.test(line)) {
      flushList();
      flushPara();
      out.push('<hr>');
      continue;
    }

    // Checkboxes (- [x] / - [ ] / - [X])
    const checkbox = line.match(/^\s*[-*]\s+\[([ xX])\]\s+(.+)$/);
    if (checkbox) {
      flushList();
      flushPara();
      const mark = checkbox[1].toLowerCase() === 'x' ? '☑' : '☐';
      out.push(`<div>${mark} ${inline(checkbox[2])}</div>`);
      continue;
    }

    // Ordered list (1. item) — leading whitespace allowed (continuation lines)
    const ordered = line.match(/^\s*\d+\.\s+(.+)$/);
    if (ordered) {
      flushPara();
      if (list && list.tag !== 'ol') flushList();
      if (!list) list = { tag: 'ol', items: [] };
      list.items.push(inline(ordered[1]));
      continue;
    }

    // Unordered list (- item / * item)
    const unordered = line.match(/^\s*[-*]\s+(.+)$/);
    if (unordered) {
      flushPara();
      if (list && list.tag !== 'ul') flushList();
      if (!list) list = { tag: 'ul', items: [] };
      list.items.push(inline(unordered[1]));
      continue;
    }

    // Blank line: paragraph / list boundary
    if (/^\s*$/.test(line)) {
      flushList();
      flushPara();
      continue;
    }

    // Plain paragraph text (single newlines become <br>)
    flushList();
    para.push(inline(line));
  }
  flushList();
  flushPara();

  return out.join('');
}
