/**
 * Convert simple markdown to HTML suitable for ADO work item fields.
 * ADO expects HTML in System.Description and AcceptanceCriteria fields.
 * This handles the common markdown patterns generated by LLMs in task details:
 * - Headings (#, ##, ###)
 * - Bold (**text**)
 * - Italic (*text*)
 * - Unordered lists (- item)
 * - Ordered lists (1. item)
 * - Line breaks
 * - Code blocks and inline code
 * - Links
 */

export function markdownToHtml(md: string): string {
  if (!md) return '';

  let html = md;

  // Escape HTML entities first (we don't want markdown to produce XSS)
  html = html
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  // Code blocks (``` ... ```) - must come before other transformations
  html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (_, lang, code) => {
    const langAttr = lang ? ` class="language-${lang}"` : '';
    return `<pre><code${langAttr}>${code.trim()}</code></pre>`;
  });

  // Inline code (`code`)
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>');

  // Headings (## and ### only - keep it simple for ADO)
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');

  // Bold and italic
  html = html.replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>');
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');

  // Links [text](url)
  html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');

  // Checkboxes
  html = html.replace(/^- \[x\] (.+)$/gm, '<div>☑ $1</div>');
  html = html.replace(/^- \[ \] (.+)$/gm, '<div>☐ $1</div>');

  // Unordered lists (- item or * item)
  html = html.replace(/^[-*] (.+)$/gm, '<li>$1</li>');
  html = html.replace(/(<li>.*<\/li>\n?)+/g, (match) => `<ul>${match}</ul>`);

  // Ordered lists (1. item)
  html = html.replace(/^\d+\. (.+)$/gm, '<li>$1</li>');
  // Wrap consecutive <li> that came from ordered lists (rough heuristic)
  html = html.replace(/(<li>.*<\/li>\n?)+/g, (match) => {
    // Check if original had numbers - if we already wrapped as ul, skip
    if (match.includes('<ul>')) return match;
    return `<ol>${match}</ol>`;
  });

  // Horizontal rule
  html = html.replace(/^[-*_]{3,}$/gm, '<hr>');

  // Line breaks (double newline = paragraph, single = <br>)
  html = html.replace(/\n\n/g, '</p><p>');
  html = html.replace(/\n/g, '<br>');

  // Wrap in paragraph if not already wrapped
  if (!html.startsWith('<')) {
    html = `<p>${html}</p>`;
  }

  return html;
}
